### PR TITLE
Multi-server fixtures

### PR DESCRIPTION
**Pull request by josiah-wolf-oberholtzer**
Parameterize the `server` fixture to run both `scsynth` and `supernova`,

### CODE REVIEW

**Comment by gitmarek** [comment]
I got interested in why several tests fail on supernova.  One of them (`test_Buffer.py::test___plot___01`) is easy to fix: 7337ead71290e699de7290fdf770ab64844939b3

Another test (`tests/realtime/test_Group.py::test___setitem___04`) I wasn't able to fix.  One of the synths is not transferred to a new group (line [933](https://github.com/josiah-wolf-oberholtzer/supriya/blob/main/tests/realtime/test_Group.py#L933)).  I checked, and the same thing happens for `sclang`.  If I execute the code:

```
s = Server.default()
s.boot()


g = Group()
h = Group()

(
SynthDef(\test, {
	Out.ar(10, SinOsc.ar())
}).add;
)

~aa = {Synth(\test, target: g)} !4
~aa[0].moveToHead(h)
~aa[1].moveAfter(~aa[0])
s.queryAllNodes
```

with `scsynth`, I get the structure:
```
// scsynth
NODE TREE Group 0
   1 group
      1001 group
         1002 test
         1003 test
      1000 group
         1005 test
         1004 test
```

Whereas for `supernova`:
```
// supernova
NODE TREE Group 0
   0 group
      1 group
         1001 group
            1002 test
         1000 group
            1005 test
            1004 test
            1003 test
```

is is a bug in `supernova`?

**Comment by josiah-wolf-oberholtzer** [comment]
Could definitely be a bug with supernova, yeah.

I would try isolating down to an even simpler test case. Two synths. Move one before or after the other and see if supernova respects the commands.

Would also double-check the timing. Maybe supernova is respecting the commands, but reports the state at a slightly different moment than scsynth?

**Comment by josiah-wolf-oberholtzer** [comment]
Run this one-liner (swapping `supernova` for `scsynth` and vice-versa) and it seems like both behave fine:

```
import supriya; supriya._setup_logging("supriya.osc.out", "supriya.server"); server = supriya.Server().boot(executable="supernova"); group = server.add_group(); synth_a = supriya.Synth(); synth_b = supriya.Synth(); group[:] = [synth_a, synth_b]; print(server.query()); group[1:-1] = [synth_b, synth_a]; print(server.query())
```

Verbose log output show how Supriya's converting the `[1:-1] = [synth_b, synth_a]` into a pair of `[/g_head, /n_after]` commands:

```
2022-11-16 17:01:21,742 - supriya.osc.out - DEBUG - 127.0.0.1:57110 OscMessage('/g_new', 1000, 0, 1)
2022-11-16 17:01:21,751 - supriya.osc.out - DEBUG - 127.0.0.1:57110 OscMessage('/d_recv', bytearray(b'SCgf\x00\x00\x00\x02\x00\x01\x07default\x00\x00\x00\x0c\x00\x00\x00\x00>\x99\x99\x9a<#\xd7\n?333@\x00\x00\x00\xbe\xcc\xcc\xcd>\xcc\xcc\xcdEz\x00\x00E\x9c@\x00E\x1c@\x00EH\x00\x00?\x80\x00\x00\x00\x00\x00\x05\x00\x00\x00\x00=\xcc\xcc\xcdC\xdc\x00\x00?\x80\x00\x00?\x00\x00\x00\x00\x00\x00\x05\tamplitude\x00\x00\x00\x01\tfrequency\x00\x00\x00\x02\x04gate\x00\x00\x00\x03\x03out\x00\x00\x00\x00\x03pan\x00\x00\x00\x04\x00\x00\x00\x14\x07Control\x00\x00\x00\x00\x00\x00\x00\x00\x01\x00\x00\x00\x07Control\x01\x00\x00\x00\x00\x00\x00\x00\x04\x00\x01\x01\x01\x01\x01\x06VarSaw\x02\x00\x00\x00\x03\x00\x00\x00\x01\x00\x00\x00\x00\x00\x01\x00\x00\x00\x01\xff\xff\xff\xff\x00\x00\x00\x00\xff\xff\xff\xff\x00\x00\x00\x01\x02\x05Linen\x01\x00\x00\x00\x05\x00\x00\x00\x01\x00\x00\x00\x00\x00\x01\x00\x00\x00\x02\xff\xff\xff\xff\x00\x00\x00\x02\xff\xff\xff\xff\x00\x00\x00\x03\xff\xff\xff\xff\x00\x00\x00\x01\xff\xff\xff\xff\x00\x00\x00\x04\x01\x04Rand\x00\x00\x00\x00\x02\x00\x00\x00\x01\x00\x00\xff\xff\xff\xff\x00\x00\x00\x05\xff\xff\xff\xff\x00\x00\x00\x00\x00\x0cBinaryOpUGen\x01\x00\x00\x00\x02\x00\x00\x00\x01\x00\x00\x00\x00\x00\x01\x00\x00\x00\x01\x00\x00\x00\x04\x00\x00\x00\x00\x01\x06VarSaw\x02\x00\x00\x00\x03\x00\x00\x00\x01\x00\x00\x00\x00\x00\x05\x00\x00\x00\x00\xff\xff\xff\xff\x00\x00\x00\x00\xff\xff\xff\xff\x00\x00\x00\x01\x02\x04Rand\x00\x00\x00\x00\x02\x00\x00\x00\x01\x00\x00\xff\xff\xff\xff\x00\x00\x00\x00\xff\xff\xff\xff\x00\x00\x00\x06\x00\x0cBinaryOpUGen\x01\x00\x00\x00\x02\x00\x00\x00\x01\x00\x00\x00\x00\x00\x01\x00\x00\x00\x01\x00\x00\x00\x07\x00\x00\x00\x00\x01\x06VarSaw\x02\x00\x00\x00\x03\x00\x00\x00\x01\x00\x00\x00\x00\x00\x08\x00\x00\x00\x00\xff\xff\xff\xff\x00\x00\x00\x00\xff\xff\xff\xff\x00\x00\x00\x01\x02\x04Sum3\x02\x00\x00\x00\x03\x00\x00\x00\x01\x00\x00\x00\x00\x00\x02\x00\x00\x00\x00\x00\x00\x00\x06\x00\x00\x00\x00\x00\x00\x00\t\x00\x00\x00\x00\x02\x0cBinaryOpUGen\x02\x00\x00\x00\x02\x00\x00\x00\x01\x00\x02\x00\x00\x00\n\x00\x00\x00\x00\xff\xff\xff\xff\x00\x00\x00\x01\x02\x04Rand\x00\x00\x00\x00\x02\x00\x00\x00\x01\x00\x00\xff\xff\xff\xff\x00\x00\x00\x07\xff\xff\xff\xff\x00\x00\x00\x08\x00\x04Rand\x00\x00\x00\x00\x02\x00\x00\x00\x01\x00\x00\xff\xff\xff\xff\x00\x00\x00\t\xff\xff\xff\xff\x00\x00\x00\n\x00\x05XLine\x01\x00\x00\x00\x04\x00\x00\x00\x01\x00\x00\x00\x00\x00\x0c\x00\x00\x00\x00\x00\x00\x00\r\x00\x00\x00\x00\xff\xff\xff\xff\x00\x00\x00\x0b\xff\xff\xff\xff\x00\x00\x00\x00\x01\x03LPF\x02\x00\x00\x00\x02\x00\x00\x00\x01\x00\x00\x00\x00\x00\x0b\x00\x00\x00\x00\x00\x00\x00\x0e\x00\x00\x00\x00\x02\x0cBinaryOpUGen\x02\x00\x00\x00\x02\x00\x00\x00\x01\x00\x02\x00\x00\x00\x0f\x00\x00\x00\x00\x00\x00\x00\x03\x00\x00\x00\x00\x02\x0cBinaryOpUGen\x02\x00\x00\x00\x02\x00\x00\x00\x01\x00\x02\x00\x00\x00\x10\x00\x00\x00\x00\x00\x00\x00\x01\x00\x00\x00\x00\x02\x04Pan2\x02\x00\x00\x00\x03\x00\x00\x00\x02\x00\x00\x00\x00\x00\x11\x00\x00\x00\x00\x00\x00\x00\x01\x00\x00\x00\x03\xff\xff\xff\xff\x00\x00\x00\x0b\x02\x02\tOffsetOut\x02\x00\x00\x00\x03\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x12\x00\x00\x00\x00\x00\x00\x00\x12\x00\x00\x00\x01\x00\x00'), OscBundle(
    contents=(
        OscMessage('/s_new', 'default', 1001, 0, 1000),
        OscMessage('/s_new', 'default', 1002, 3, 1001),
    ),
))
2022-11-16 17:01:21,758 - supriya.osc.out - DEBUG - 127.0.0.1:57110 OscMessage('/g_queryTree', 0, 1)
NODE TREE 0 group
    1 group
        1000 group
            1001 default
                out: 0.0, amplitude: 0.1, frequency: 440.0, gate: 1.0, pan: 0.5
            1002 default
                out: 0.0, amplitude: 0.1, frequency: 440.0, gate: 1.0, pan: 0.5
2022-11-16 17:01:21,764 - supriya.osc.out - DEBUG - 127.0.0.1:57110 OscBundle(
    contents=(
        OscMessage('/g_head', 1000, 1002),
        OscMessage('/n_after', 1001, 1002),
        OscMessage('/sync', 0),
    ),
)
2022-11-16 17:01:21,768 - supriya.osc.out - DEBUG - 127.0.0.1:57110 OscMessage('/g_queryTree', 0, 1)
NODE TREE 0 group
    1 group
        1000 group
            1002 default
                out: 0.0, amplitude: 0.1, frequency: 440.0, gate: 1.0, pan: 0.5
            1001 default
                out: 0.0, amplitude: 0.1, frequency: 440.0, gate: 1.0, pan: 0.5
```

I'm willing to bet there's just something weird about my tests. That's some of the oldest code in Supriya, so not surprised if it's not as well-crafted as some of the later code.

**Comment by gitmarek** [comment]
I couldn't find an error in the tests either.  I played around with `supernova`, and the tree structure doesn't look like what I'd expect from `.moveToHead()`.  Especially the last query:

```
s.quit()
Server.supernova
s = Server.default()
s.waitForBoot( SynthDef(\test, { Out.ar(10, SinOsc.ar())} ).add; )

g = Group()
h = Group(addAction: 'addToTail')

a = Synth(\test, target: g, addAction: 'addToTail')
b = Synth(\test, target: g, addAction: 'addToTail')
c = Synth(\test, target: g, addAction: 'addToTail')

s.queryAllNodes
/*
NODE TREE Group 0
   0 group
      1 group
         1000 group
            1002 test
            1003 test
            1004 test
         1001 group
*/

a.moveToHead(h)
c.moveAfter(a)
s.queryAllNodes

/*
NODE TREE Group 0
   0 group
      1 group
         1000 group
            1003 test
            1004 test
         1001 group
            1002 test
*/

a.moveToHead(g)
b.moveToHead(h)
a.moveToHead(h)
c.moveAfter(b)
s.queryAllNodes
/*
NODE TREE Group 0
   0 group
      1 group
         1000 group
            1004 test
         1001 group
            1002 test
            1003 test
*/
c.moveAfter(a)
s.queryAllNodes
/*
NODE TREE Group 0
   0 group
      1 group
         1000 group
         1001 group
            1002 test
            1004 test
            1003 test
*/
c.moveAfter(b)
s.queryAllNodes
/*
NODE TREE Group 0
   0 group
      1 group
         1000 group
            1004 test
         1001 group
            1002 test
            1003 test
*/
s.freeAll
```

**Comment by josiah-wolf-oberholtzer** [comment]
If you think you've found a minimal repeatable error with supernova, definitely bring it to [them](https://github.com/supercollider/supercollider).

**Comment by josiah-wolf-oberholtzer** [comment]
OK, I'm convinced 😆 

Two groups, four synths, all four synths in group 1000 initially:

```
>>> server = supriya.Server().boot(executable="supernova")
>>> group_1000 = server.add_group()
>>> group_1001 = server.add_group(add_action="ADD_TO_TAIL")
>>> synth_1002 = group_1000.add_synth()
>>> synth_1003 = group_1000.add_synth()
>>> synth_1004 = group_1000.add_synth()
>>> synth_1005 = group_1000.add_synth()
>>> print(server.query()) # This looks correct
NODE TREE 0 group
    1 group
        1000 group
            1005 default
                out: 0.0, amplitude: 0.1, frequency: 440.0, gate: 1.0, pan: 0.5
            1004 default
                out: 0.0, amplitude: 0.1, frequency: 440.0, gate: 1.0, pan: 0.5
            1003 default
                out: 0.0, amplitude: 0.1, frequency: 440.0, gate: 1.0, pan: 0.5
            1002 default
                out: 0.0, amplitude: 0.1, frequency: 440.0, gate: 1.0, pan: 0.5
        1001 group
```

Reverse the order of the four synths inside group 1000:

```
>>> group_1000[:] = [synth_1002, synth_1003, synth_1004, synth_1005]
>>> print(server.query()) # This looks correct
NODE TREE 0 group
    1 group
        1000 group
            1002 default
                out: 0.0, amplitude: 0.1, frequency: 440.0, gate: 1.0, pan: 0.5
            1003 default
                out: 0.0, amplitude: 0.1, frequency: 440.0, gate: 1.0, pan: 0.5
            1004 default
                out: 0.0, amplitude: 0.1, frequency: 440.0, gate: 1.0, pan: 0.5
            1005 default
                out: 0.0, amplitude: 0.1, frequency: 440.0, gate: 1.0, pan: 0.5
        1001 group
```

Move all four synths to group 1001, but only synth 1002 moves, while the other three remain in group 1000:

```
>>> group_1001[:] = [synth_1002, synth_1003, synth_1004, synth_1005]
>>> print(server.query()) # This is incorrect: all synths should be in 1001
NODE TREE 0 group
    1 group
        1000 group
            1003 default
                out: 0.0, amplitude: 0.1, frequency: 440.0, gate: 1.0, pan: 0.5
            1004 default
                out: 0.0, amplitude: 0.1, frequency: 440.0, gate: 1.0, pan: 0.5
            1005 default
                out: 0.0, amplitude: 0.1, frequency: 440.0, gate: 1.0, pan: 0.5
        1001 group
            1002 default
                out: 0.0, amplitude: 0.1, frequency: 440.0, gate: 1.0, pan: 0.5
```

Just doing a single /n_after, to move synth 1003 after synth 1002 fails:

```
>>> synth_1002.move_node(synth_1003, "ADD_AFTER")
>>> print(server.query()) # Just doing a single /n_after is broken
NODE TREE 0 group
    1 group
        1000 group
            1004 default
                out: 0.0, amplitude: 0.1, frequency: 440.0, gate: 1.0, pan: 0.5
            1005 default
                out: 0.0, amplitude: 0.1, frequency: 440.0, gate: 1.0, pan: 0.5
            1003 default
                out: 0.0, amplitude: 0.1, frequency: 440.0, gate: 1.0, pan: 0.5
        1001 group
            1002 default
                out: 0.0, amplitude: 0.1, frequency: 440.0, gate: 1.0, pan: 0.5
```

But doing an /n_before to move synth 1003 before synth 1002 inside group 1001 succeeds

```
>>> synth_1002.move_node(synth_1003, "ADD_BEFORE")
>>> print(server.query()) # But /n_before works
NODE TREE 0 group
    1 group
        1000 group
            1004 default
                out: 0.0, amplitude: 0.1, frequency: 440.0, gate: 1.0, pan: 0.5
            1005 default
                out: 0.0, amplitude: 0.1, frequency: 440.0, gate: 1.0, pan: 0.5
        1001 group
            1003 default
                out: 0.0, amplitude: 0.1, frequency: 440.0, gate: 1.0, pan: 0.5
            1002 default
                out: 0.0, amplitude: 0.1, frequency: 440.0, gate: 1.0, pan: 0.5
```

And now that synth 1003 is inside group 1001, we can do the /n_after successfully:

```
>>> synth_1002.move_node(synth_1003, "ADD_AFTER")
>>> print(server.query())
NODE TREE 0 group
    1 group
        1000 group
            1004 default
                out: 0.0, amplitude: 0.1, frequency: 440.0, gate: 1.0, pan: 0.5
            1005 default
                out: 0.0, amplitude: 0.1, frequency: 440.0, gate: 1.0, pan: 0.5
        1001 group
            1002 default
                out: 0.0, amplitude: 0.1, frequency: 440.0, gate: 1.0, pan: 0.5
            1003 default
                out: 0.0, amplitude: 0.1, frequency: 440.0, gate: 1.0, pan: 0.5
```

**Comment by josiah-wolf-oberholtzer** [comment]
For posterity: https://github.com/supercollider/supercollider/issues/5909

**Pull request closed without merging**
