### PR TITLE
Allow passing tuples of floats to `def add_synth`

### PR DESCRIPTION
**Pull request by arp2600**
This enables passing tuples of floats to `Group.add_synth`. For example:
```
@synthdef()
def test_synth(freq=(220, 440)):
    sig = SinOsc.ar(frequency=freq) * 0.5
    sig = Mix.new(sig)
    Out.ar(bus=0, source=[sig, sig])

_ = server.add_synthdefs(test_synth)
server.sync()

group.add_synth(test_synth, freq=(220.0, 330))
```

### CODE REVIEW

**Comment by arp2600** [comment]
I'd be happy to add some tests to this. Have you got any suggestions for which tests to look at?

**Comment by josiah-wolf-oberholtzer** [comment]
To confirm, this is about a SynthDef that has an array parameter, and `add_synth()` setting that parameter when allocating a single synth?

**Comment by arp2600** [comment]
Yes, that's correct. I was trying to write a synthdef I've got in sclang using supriya and couldn't get this to work otherwise. I'm very new to using this though so not sure if I missed anything.

I've realised the error messages are now wrong as they say `argument must be a string or a number, not '...'`. I'll convert this to draft and make some changes tomorrow.

**Comment by josiah-wolf-oberholtzer** [comment]
The code looks good, but yeah, please add tests to lock it in. I'll show you what needs adjusting.

- Server.add_synth(): https://github.com/josiah-wolf-oberholtzer/supriya/blob/main/tests/contexts/test_Server_nodes.py#L155
- Score.add_synth(): https://github.com/josiah-wolf-oberholtzer/supriya/blob/main/tests/contexts/test_Score_nodes.py#L50

Both are assuming we're testing against the `default` SynthDef (defined [here](https://github.com/josiah-wolf-oberholtzer/supriya/blob/main/supriya/assets/synthdefs/default.py). If you roll your own SynthDef based on the default one, but supporting an additional array parameter, you can punch that new SynthDef into those two tests instead.

**Comment by josiah-wolf-oberholtzer** [comment]
There are some unrelated errors in GitHub Actions (linting, docs-building, Windows tests). I'm working on fixing them in a separate PR.

**Comment by josiah-wolf-oberholtzer** [comment]
Errors have been fixed. Rebase / pull latest main, and you should be back in business.

**Comment by arp2600** [comment]
I've added two test cases. Most of the other synthdefs have their own file, so I wasn't sure if I should create a new file or bundle it into `assets/synthdefs/test.py`. I went with the latter.

**Comment by josiah-wolf-oberholtzer** [comment]
Generally LGTM and works.

You'll need to address the MyPy complaints.

I also wonder if the PR should update `Context.set_node()` to permit setting arrays. Looks like the `/n_set` command supports those (http://doc.sccode.org/Reference/Server-Command-Reference.html) but that could be a separate PR.

**Comment by arp2600** [comment]
> I also wonder if the PR should update `Context.set_node()` to permit setting arrays. Looks like the `/n_set` command supports those (http://doc.sccode.org/Reference/Server-Command-Reference.html) but that could be a separate PR.

I went to add this but it looks like `set_node` already supports arrays. It's tested too:
https://github.com/josiah-wolf-oberholtzer/supriya/blob/main/tests/contexts/test_Server_nodes.py#L410
https://github.com/josiah-wolf-oberholtzer/supriya/blob/main/tests/contexts/test_Score_nodes.py#L230

**Comment by josiah-wolf-oberholtzer** [comment]
Aha, a gift from past me to future me.

**Comment by arp2600** [comment]
CI failing due to indexing not being supported for tuple in python 3.8 (introduced in 3.11). Hopefully should pass this time.

**Comment by josiah-wolf-oberholtzer** [comment]
LGTM, thanks!

**Comment by josiah-wolf-oberholtzer** [comment]
Will cut a new release soon.

**Comment by josiah-wolf-oberholtzer** [comment]
OK, your changes are available in https://github.com/josiah-wolf-oberholtzer/supriya/releases/tag/23.10b0

Thanks again.

**Pull request merged**
