### PR TITLE
Build supernova in GHA (mm)

### PR DESCRIPTION
**Pull request by gitmarek**

### CODE REVIEW

**Comment by gitmarek** [comment]
Building supernova fails on macOS only.  There's is a problem with linking to portaudio:

[https://github.com/josiah-wolf-oberholtzer/supriya/actions/runs/3341970069/jobs/5533710335#step:7:5098](https://github.com/josiah-wolf-oberholtzer/supriya/actions/runs/3341970069/jobs/5533710335#step:7:5098)

I don't know anything about macOS or portaudio, so I'm going to leave it as is here.

**Comment by josiah-wolf-oberholtzer** [comment]
Couple questions:
- Why don't we see the `SuperCollider 3 server ready.` message like we used to here: https://github.com/josiah-wolf-oberholtzer/supriya/actions/runs/3339055900/jobs/5527518437#step:5:2392`?
- Any idea why jack is much chattier in this PR versus before?
- Can we confirm that we _really_ have to start jackd three times? Having to restart after every scsynth / supernova run is gonna be a non-starter for CI/CD.

**Comment by gitmarek** [comment]
You're right -- that looks messy.  I'll try to have only one copy of `jackd` running.

**Comment by josiah-wolf-oberholtzer** [comment]
Hey, this LGTM. Thanks for figuring out the OSX stuff, and for keeping the log output as clean as possible. 🙏

**Review by josiah-wolf-oberholtzer — APPROVED** [review]

**Pull request merged**
