### PR TITLE
Build supernova in GHA

### PR DESCRIPTION
**Pull request by josiah-wolf-oberholtzer**

### CODE REVIEW

**Comment by josiah-wolf-oberholtzer** [comment]
> 👍

Not until we prove it works 😅

**Review by gitmarek — COMMENTED** [review]
Trying out github-dev now...

**Review by gitmarek — COMMENTED** [review]
Respawn jackd one more time?

**Review by gitmarek — APPROVED** [review]

**Comment by gitmarek** [comment]
I couldn't figure out if it's possible here for me to amend the PR (probably not), so I started my own #274.

**Comment by josiah-wolf-oberholtzer** [comment]
Superseded by #273

**Pull request closed without merging**
